# -*- coding: utf-8 -*-
"""Lab4-2_Music Playlist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJlZomNxce2LCx6uFSv3p4EiT4OTxo5y

#Lab4-2 การนำ Linked List มาใช้งาน

### Music Playlist

First, let's define the `Song` class. Each `Song` object will represent a node in our linked list, containing song details and a pointer to the next song.
"""

class Song:
    def __init__(self, title, artist):
        self.title = title
        self.artist = artist
        self.next_song = None

    def __str__(self):
        return f"{self.title} by {self.artist}"

"""Next, we'll define the `MusicPlaylist` class, which will manage the collection of `Song` objects using a linked list. It will have methods to add songs, display the playlist, and optionally play songs (though 'playing' here is just printing the song details)."""

class MusicPlaylist:
    def __init__(self):
        self.head = None  # The head of the linked list (first song)
        self.current_song = None # To keep track of the currently playing song
        self.length = 0

    def add_song(self, title, artist):
        new_song = Song(title, artist)
        if self.head is None:
            self.head = new_song
            self.current_song = new_song # If first song, it's also the current one
        else:
            current = self.head
            while current.next_song:
                current = current.next_song
            current.next_song = new_song
        self.length += 1
        print(f"Added: {new_song}")

    def display_playlist(self):
        if self.head is None:
            print("Playlist is empty.")
            return

        current = self.head
        print("\n--- Your Music Playlist ---")
        count = 1
        while current:
            print(f"{count}. {current}")
            current = current.next_song
            count += 1
        print("---------------------------")

    def play_current_song(self):
        if self.current_song:
            print(f"\nNow playing: {self.current_song}")
        else:
            print("Playlist is empty or no song is selected to play.")

    def next_song(self):
        if self.current_song and self.current_song.next_song:
            self.current_song = self.current_song.next_song
            self.play_current_song()
        elif self.current_song and not self.current_song.next_song:
            print("End of playlist. No next song.")
        else:
            print("Playlist is empty.")

    def prev_song(self):
        if self.head is None or self.current_song is None:
            print("Playlist is empty or no song is selected.")
            return
        if self.current_song == self.head:
            print("Already at the beginning of the playlist.")
            return

        current = self.head
        while current.next_song != self.current_song:
            current = current.next_song
        self.current_song = current
        self.play_current_song()

    def get_length(self):
        return self.length

    def delete_song(self, title):
        if self.head is None:
            print(f"Cannot delete '{title}'. Playlist is empty.")
            return

        # If the song to be deleted is the head
        if self.head.title == title:
            if self.current_song == self.head:
                self.current_song = self.head.next_song
            self.head = self.head.next_song
            self.length -= 1
            print(f"Deleted: {title}")
            if self.length == 0:
                self.current_song = None
            return

        current = self.head
        prev = None
        while current and current.title != title:
            prev = current
            current = current.next_song

        if current:
            if self.current_song == current:
                # If the deleted song was the current song, try to set the next song as current
                # If no next, then previous. If no previous, then current becomes None.
                if current.next_song:
                    self.current_song = current.next_song
                elif prev:
                    self.current_song = prev
                else:
                    self.current_song = None # Only one song, and it was deleted

            prev.next_song = current.next_song
            self.length -= 1
            print(f"Deleted: {title}")
        else:
            print(f"Song '{title}' not found in the playlist.")

"""Now, let's demonstrate how to use these classes to create and manage a music playlist."""

# Create a new playlist
my_playlist = MusicPlaylist()

# Add some songs
my_playlist.add_song("Bohemian Rhapsody", "Queen")
my_playlist.add_song("Stairway to Heaven", "Led Zeppelin")
my_playlist.add_song("Hotel California", "Eagles")
my_playlist.add_song("Imagine", "John Lennon")

# Display the entire playlist
my_playlist.display_playlist()

# Play the current song (which should be the first one added)
my_playlist.play_current_song()

# Move to the next song and play it
my_playlist.next_song()

# Move to the next song again
my_playlist.next_song()

# Go back to the previous song
my_playlist.prev_song()

# Try to go back again (should indicate already at beginning)
my_playlist.prev_song()

# Move to the end of the playlist
my_playlist.next_song()
my_playlist.next_song()
my_playlist.next_song()

# Try to move next from the end
my_playlist.next_song()

# Check playlist length
print(f"\nPlaylist length: {my_playlist.get_length()} songs")

# Delete a song that exists
my_playlist.delete_song("Stairway to Heaven")
my_playlist.delete_song("Hotel California")
my_playlist.display_playlist()

# Play the current song (which should be the first one added)
my_playlist.play_current_song()

# Try to move next from the end
my_playlist.next_song()

# Check playlist length
print(f"\nPlaylist length: {my_playlist.get_length()} songs")

my_playlist2 = MusicPlaylist()
my_playlist2.add_song("sunday morning", "Marmoon 5")
my_playlist2.add_song("PHOM BLONDE", "spingy")
my_playlist2.play_current_song()
my_playlist2.next_song()
my_playlist2.next_song()
my_playlist2.next_song()

"""#สร้าง Web App

1. installing **streamlit** and **pyngrok** libraries
"""

pip install streamlit pyngrok

"""2. สร้างไฟล์ .py"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# # --- Song Class ---
# class Song:
#     def __init__(self, title, artist, audio_file):
#         self.title = title
#         self.artist = artist
#         self.audio_file = audio_file
#         self.next_song = None
# 
#     def __str__(self):
#         return f"{self.title} by {self.artist}"
# 
# # --- MusicPlaylist Class ---
# class MusicPlaylist:
#     def __init__(self):
#         self.head = None
#         self.current_song = None
#         self.length = 0
# 
#     def add_song(self, title, artist, audio_file):
#         new_song = Song(title, artist, audio_file)
#         if self.head is None:
#             self.head = new_song
#             self.current_song = new_song
#         else:
#             current = self.head
#             while current.next_song:
#                 current = current.next_song
#             current.next_song = new_song
#         self.length += 1
#         st.success(f"Added: {new_song}")
# 
#     def display_playlist(self):
#         if self.head is None:
#             return []
# 
#         playlist_songs = []
#         current = self.head
#         count = 1
#         while current:
#             playlist_songs.append(f"{count}. {current.title} by {current.artist}")
#             current = current.next_song
#             count += 1
#         return playlist_songs
# 
#     def play_current_song(self):
#         if self.current_song:
#             st.info(f"Now playing: {self.current_song}")
#             if self.current_song.audio_file:
#                 st.audio(self.current_song.audio_file, format='audio/mp3')
#         else:
#             st.warning("Playlist is empty or no song is selected to play.")
# 
#     def next_song(self):
#         if self.current_song and self.current_song.next_song:
#             self.current_song = self.current_song.next_song
#         elif self.current_song and not self.current_song.next_song:
#             st.warning("End of playlist. No next song.")
#         else:
#             st.warning("Playlist is empty.")
# 
#     def prev_song(self):
#         if self.head is None or self.current_song is None:
#             st.warning("Playlist is empty or no song is selected.")
#             return
#         if self.current_song == self.head:
#             st.warning("Already at the beginning of the playlist.")
#             return
# 
#         current = self.head
#         while current.next_song != self.current_song:
#             current = current.next_song
#         self.current_song = current
# 
#     def get_length(self):
#         return self.length
# 
#     def delete_song(self, title):
#         if self.head is None:
#             st.error(f"Cannot delete '{title}'. Playlist is empty.")
#             return
# 
#         # If the song to be deleted is the head
#         if self.head.title == title:
#             if self.current_song == self.head:
#                 self.current_song = self.head.next_song
#             self.head = self.head.next_song
#             self.length -= 1
#             st.success(f"Deleted: {title}")
#             if self.length == 0:
#                 self.current_song = None
#             return
# 
#         current = self.head
#         prev = None
#         while current and current.title != title:
#             prev = current
#             current = current.next_song
# 
#         if current:
#             if self.current_song == current:
#                 if current.next_song:
#                     self.current_song = current.next_song
#                 elif prev:
#                     self.current_song = prev
#                 else:
#                     self.current_song = None
# 
#             prev.next_song = current.next_song
#             self.length -= 1
#             st.success(f"Deleted: {title}")
#         else:
#             st.error(f"Song '{title}' not found in the playlist.")
# 
# # --- Streamlit App Layout ---
# st.title("🎶 Music Playlist App")
# 
# # Initialize playlist in session state
# if 'playlist' not in st.session_state:
#     st.session_state.playlist = MusicPlaylist()
# 
# # Sidebar for adding songs
# st.sidebar.header("Add New Song")
# new_title = st.sidebar.text_input("Title")
# new_artist = st.sidebar.text_input("Artist")
# audio_file = st.sidebar.file_uploader("Upload Audio File", type=["mp3"])
# 
# if st.sidebar.button("Add Song to Playlist"):
#     if new_title and new_artist and audio_file:
#         st.session_state.playlist.add_song(new_title, new_artist, audio_file)
#     else:
#         st.sidebar.warning("Please enter both title and artist and upload an audio file.")
# 
# st.sidebar.markdown("--- 🎶")
# st.sidebar.header("Delete Song")
# delete_title = st.sidebar.text_input("Song Title to Delete")
# if st.sidebar.button("Delete Song"):
#     if delete_title:
#         st.session_state.playlist.delete_song(delete_title)
#     else:
#         st.sidebar.warning("Please enter a song title to delete.")
# 
# # Main content for playlist display and controls
# st.header("Your Current Playlist")
# playlist_content = st.session_state.playlist.display_playlist()
# if playlist_content:
#     for song_str in playlist_content:
#         st.write(song_str)
# else:
#     st.write("Playlist is empty. Add some songs from the sidebar!")
# 
# st.markdown("--- 🎶")
# st.header("Playback Controls")
# col1, col2, col3 = st.columns(3)
# 
# with col1:
#     if st.button("⏪ Previous"):
#         st.session_state.playlist.prev_song()
#         st.session_state.playlist.play_current_song()
# 
# with col2:
#     if st.button("▶️ Play Current"):
#         st.session_state.playlist.play_current_song()
# 
# with col3:
#     if st.button("⏩ Next"):
#         st.session_state.playlist.next_song()
#         st.session_state.playlist.play_current_song()
# 
# st.markdown("--- 🎶")
# st.write(f"Total songs in playlist: {st.session_state.playlist.get_length()} song(s)")

"""3. Login **ngrok** ที่ https://ngrok.com/ and copy your **authtoken**"""

!ngrok authtoken YOUR_TOKEN

from pyngrok import ngrok

ngrok.kill()  # ปิด tunnel เก่า

public_url = ngrok.connect(8501)
print("🌍 Open your app here:", public_url)

"""4. **รัน app Streamlit** ที่สร้างขึ้นมา
การบอกให้ Colab รันไฟล์ calculator.py ด้วย Streamlit บนพอร์ต 8501
"""

!streamlit run app.py --server.port 8501 &